name: CD Pipeline Vercel

on:
  workflow_run: 
    workflows: ["CI Pipeline"]
    types:
      - completed 
  push: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    if: |
      github.event_name == 'push' && github.ref == 'refs/heads/main' ||
      github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Vercel CLI
      run: npm install --global vercel@latest 

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      env:
        VERCEL_ORG_ID: Re4qAN5FmJsKBBOfBvVYEvpm
        VERCEL_PROJECT_ID: prj_PvrPUHV40ku4qOMCWz6cS2LWyQxv 

    - name: Deploy to Vercel
      run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
      env:
        VERCEL_ORG_ID: Re4qAN5FmJsKBBOfBvVYEvpm
        VERCEL_PROJECT_ID: prj_PvrPUHV40ku4qOMCWz6cS2LWyQxv 
