name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/**
      - bugfix/**
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint: # Job pertama untuk linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit --audit-level=high
        continue-on-error: true # Ini akan melanjutkan meskipun ada kerentanan

      - name: Make ESLint executable
        run: chmod +x ./node_modules/.bin/eslint

      - name: Run ESLint
        run: npm run lint

  test: # Job kedua untuk testing
    runs-on: ubuntu-latest
    needs: lint # Ini memastikan job 'test' akan berjalan setelah 'lint' selesai dengan sukses
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Make Jest executable
        run: chmod +x ./node_modules/.bin/jest

      - name: Run Tests
        run: npm test